// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataTrackingProto.proto

package Genprotos;

public interface DataTrackingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataTracking)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>required string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>required string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required fixed64 timestamp = 3;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>required fixed64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>optional string phone_id = 4;</code>
   * @return Whether the phoneId field is set.
   */
  boolean hasPhoneId();
  /**
   * <code>optional string phone_id = 4;</code>
   * @return The phoneId.
   */
  java.lang.String getPhoneId();
  /**
   * <code>optional string phone_id = 4;</code>
   * @return The bytes for phoneId.
   */
  com.google.protobuf.ByteString
      getPhoneIdBytes();

  /**
   * <code>optional fixed64 lon = 5;</code>
   * @return Whether the lon field is set.
   */
  boolean hasLon();
  /**
   * <code>optional fixed64 lon = 5;</code>
   * @return The lon.
   */
  long getLon();

  /**
   * <code>optional fixed64 lat = 6;</code>
   * @return Whether the lat field is set.
   */
  boolean hasLat();
  /**
   * <code>optional fixed64 lat = 6;</code>
   * @return The lat.
   */
  long getLat();
}
