/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package with_code_gen;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Gender { 
  Male, female  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"with_code_gen\",\"symbols\":[\"Male\",\"female\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
